import Head from "next/head";
import { Navbar } from "../components";
import Image from "next/image";
import {
	ExampleProject,
	GlassEmail,
	GlassGithub,
	GlassInstragram,
	GlassLinkedIn,
	IconClock,
	IconDownload,
	IconFigma,
	IconProjectWeb,
	LineArt,
	ProfileHome,
	ProfileHome2,
} from "assets/icon/home";
import { useRef, useState } from "react";
import {
	AboutSvg,
	ContactSvg,
	HomeSvg,
	LinkSvg,
	ProjectSvg,
} from "assets/icon/home/compSvg";
import { BottomSheet } from "react-spring-bottom-sheet";
import "react-spring-bottom-sheet/dist/style.css";
import Link from "next/link";
import { Ahref } from "config";

export default function Home() {
	const [tabProjects, setTabProjects] = useState("tab1");

	const CompSocmed = (props) => {
		const [showSocmed, setShowSocmed] = useState(false);

		return (
			<Link href={props.href}>
				<a
					onMouseEnter={() => setShowSocmed(true)}
					onMouseLeave={() => setShowSocmed(false)}
					target="_blank"
					rel="noreferrer"
					className="flex flex-row"
				>
					<div className="relative w-10 z-[1] h-10">
						<Image src={props.src} layout="fill" alt="" />
					</div>
					<div
						className={`${
							showSocmed
								? " pr-3 -ml-6 pl-9 w-40 border border-white/10"
								: "w-0"
						} flex justify-between py-2 rounded-xl bg-brand/10 backdrop-blur-3xl duration-1000 overflow-hidden`}
					>
						{showSocmed && (
							<>
								<span className="text-sm font-medium text-white-1">
									{props.name}
								</span>
								<LinkSvg className="w-5 h-5 fill-white" />
							</>
						)}
					</div>
				</a>
			</Link>
		);
	};

	return (
		<div className="">
			<Head>
				<title>Sindev - Portfolio</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Navbar />
			<div className="relative overflow-hidden bg-main-dark">
				<div
					id="hero"
					className="h-screen relative w-full bg-gradient-to-b from-[#171045] to-transparent"
				>
					<div className="absolute w-72 h-72 sm:w-96 sm:h-96 -bottom-20 lg:-bottom-32 -left-40 z-[1]">
						<Image layout="fill" src={LineArt} alt="line sindev" />
					</div>
					<div className="flex flex-col items-center justify-center h-full max-w-6xl px-4 mx-auto space-y-4 xl:px-0 lg:space-y-0 lg:flex-row lg:justify-between">
						<div className="flex flex-col justify-center w-full space-y-3 sm:space-y-5 lg:h-full lg:w-7/12">
							<div className="flex flex-col">
								<h1 className="text-base text-white-1 lg:text-xl">
									Hallo, I am Singgih
								</h1>
								<p className="text-3xl md:text-6xl text-transparent font-bold bg-clip-text bg-gradient-to-l from-[#aa3ff1] to-[#4628F1] animate-text">
									Front End Developer
								</p>
							</div>
							<p className="text-sm lg:text-base text-white-1 sm:w-[75%]">
								I’m a top online marketer and branding expert, I started my
								career by lauching the popular metaverse design, in just a few
								short years, I built the brand to millions of social media
								followers and websites visitors.
							</p>
							<div className="flex flex-row space-x-5">
								<a href="https://id.linkedin.com/in/singgih-budi-purnadi-620751195?trk=people-guest_people_search-card&original_referer=https%3A%2F%2Fwww.google.com%2F">
									<div className="px-5 py-2 text-sm text-center sm:w-48 hover:bg-brand/30 bg-brand text-white-1 sm:text-base rounded-xl">
										Hire Me!
									</div>
								</a>
								<button className="flex justify-center px-5 py-2 space-x-3 border sm:w-48 rounded-xl border-brand hover:bg-brand/30">
									<span className="text-sm sm:text-base text-white-1">
										Download CV
									</span>
									<div className="relative w-5 h-5">
										<Image
											layout="fill"
											src={IconDownload}
											alt="icon download sindev"
										/>
									</div>
								</button>
							</div>
						</div>
						<div className="relative w-72 h-72 sm:w-96 sm:h-96">
							<Image layout="fill" src={ProfileHome} alt=" profile sindev" />
						</div>
					</div>
				</div>
				<section
					id="about"
					className="relative justify-between w-full sm:h-screen bg-main-dark"
				>
					<div className="absolute rotate-180 w-72 h-72 sm:w-96 sm:h-96 -bottom-4 lg:-top-32 -right-40">
						<Image layout="fill" src={LineArt} alt="line sindev" />
					</div>
					<div className="flex flex-col items-center justify-center max-w-6xl px-4 py-20 mx-auto space-y-4 sm:py-24 lg:space-y-0 lg:justify-between lg:flex-row-reverse xl:px-0">
						<div className="flex flex-col justify-center w-full space-y-8 sm:space-y-12 lg:h-full lg:w-6/12">
							<div className="flex flex-col space-y-1 sm:space-y-2">
								<h2 className="text-2xl font-bold md:text-4xl text-brand">
									About Me
								</h2>
								<p className="text-sm lg:text-base text-white-1">
									I’m a top online marketer and branding expert, I started my
									career by lauching the popular metaverse design, in just a few
									short years, I built the brand to millions of social media
									followers and websites visitors. I also created award-winning
									online products with millions of dolloars in online sales you
									want, you never get personalized experiences and they can be
									upwards of $1000 on hour.
								</p>
							</div>
							<div className="grid grid-cols-2 gap-5 sm:grid-cols-3">
								<div className="flex flex-row items-center space-x-3">
									<div className="flex items-center justify-center w-8 h-8 sm:w-10 sm:h-10 rounded-xl bg-brand/30">
										<div className="relative w-6 h-6 sm:w-8 sm:h-8">
											<Image layout="fill" src={IconClock} alt="clock sindev" />
										</div>
									</div>
									<div className="flex flex-col">
										<span className="text-base font-bold sm:text-lg text-brand">
											2 Years+
										</span>
										<span className="text-sm sm:text-base text-white-1">
											Experiences
										</span>
									</div>
								</div>
								<div className="flex flex-row items-center space-x-3">
									<div className="flex items-center justify-center w-8 h-8 sm:w-10 sm:h-10 rounded-xl bg-brand/30">
										<div className="relative w-6 h-6 sm:w-8 sm:h-8">
											<Image
												layout="fill"
												src={IconProjectWeb}
												alt="clock sindev"
											/>
										</div>
									</div>
									<div className="flex flex-col">
										<span className="text-base font-bold sm:text-lg text-brand">
											10 Projects+
										</span>
										<span className="text-sm sm:text-base text-white-1">
											Front End Dev
										</span>
									</div>
								</div>
								<div className="flex flex-row items-center space-x-3">
									<div className="flex items-center justify-center w-8 h-8 sm:w-10 sm:h-10 rounded-xl bg-brand/30">
										<div className="relative w-6 h-6 sm:w-8 sm:h-8">
											<Image layout="fill" src={IconFigma} alt="clock sindev" />
										</div>
									</div>
									<div className="flex flex-col">
										<span className="text-base font-bold sm:text-lg text-brand">
											5 Projects+
										</span>
										<span className="text-sm sm:text-base text-white-1">
											UI/UX
										</span>
									</div>
								</div>
							</div>
							<div className="flex flex-row space-x-5">
								<a href="https://id.linkedin.com/in/singgih-budi-purnadi-620751195?trk=people-guest_people_search-card&original_referer=https%3A%2F%2Fwww.google.com%2F">
									<div className="px-5 py-2 text-sm text-center sm:w-48 hover:bg-brand/30 bg-brand text-white-1 sm:text-base rounded-xl">
										Hire Me!
									</div>
								</a>
								<button className="flex justify-center px-5 py-2 space-x-3 border sm:w-48 rounded-xl border-brand hover:bg-brand/30">
									<span className="text-sm sm:text-base text-white-1">
										Download CV
									</span>
									<div className="relative w-5 h-5">
										<Image
											layout="fill"
											src={IconDownload}
											alt="icon download sindev"
										/>
									</div>
								</button>
							</div>
						</div>
						<div className="relative w-72 h-72 sm:w-96 sm:h-96">
							<Image layout="fill" src={ProfileHome2} alt="profile sindev" />
						</div>
					</div>
				</section>
				<section
					id="project"
					className="max-w-6xl px-4 pt-20 pb-40 mx-auto space-y-2 sm:py-20 sm:h-screen xl:px-0 sm:space-y-8"
				>
					<h2 className="text-2xl font-bold text-center md:text-4xl text-brand">
						Projects
					</h2>
					<div className="flex flex-col">
						<div className="flex flex-row justify-start mt-2 ml-8 space-x-1">
							<button
								onClick={() => setTabProjects("tab1")}
								className={` ${
									tabProjects === "tab1"
										? "text-white-1 font-bold text-base sm:text-xl bg-brand/10 rounded-t-xl"
										: "text-brand text-sm sm:text-base font-medium underline"
								} px-3 py-2 transition-all`}
							>
								Web Developer
							</button>
							<button
								onClick={() => setTabProjects("tab2")}
								className={` ${
									tabProjects === "tab2"
										? "text-white-1 font-bold text-base sm:text-xl bg-brand/10 rounded-t-xl"
										: "text-brand text-sm sm:text-base font-medium underline"
								} px-3 py-2 transition-all`}
							>
								Web Design
							</button>
						</div>
						<div className="w-full px-4 sm:px-12 lg:px-24 py-10 bg-brand/10 rounded-[36px] overflow-hidden">
							{tabProjects === "tab1" ? (
								<div className="flex justify-center">
									<div className="grid grid-cols-1 gap-10 sm:grid-cols-2 lg:grid-cols-3">
										<div className="flex flex-col space-y-5 w-72">
											<div className="relative w-full overflow-hidden h-52 rounded-3xl">
												<Image
													layout="fill"
													src={ExampleProject}
													alt="project litedex"
												/>
											</div>
											<div className="flex flex-col p-1 space-y-3">
												<span className="text-lg font-bold text-brand">
													Litedex Protocol
												</span>
												<span className="text-base text-white-1">
													Pengalaman bekerja pada bagian Front End Developer,
													UI/UX Designer dan Technical Writer.
												</span>
												<a href="" className="text-right">
													<span className="text-sm font-bold underline text-brand">
														Go to Projects
													</span>
												</a>
											</div>
										</div>
										<div className="flex flex-col space-y-5 w-72">
											<div className="relative w-full overflow-hidden bg-black h-52 rounded-3xl">
												<Image
													layout="fill"
													src={ExampleProject}
													alt="project litedex"
												/>
											</div>
											<div className="flex flex-col p-1 space-y-3">
												<span className="text-lg font-bold text-brand">
													Litedex Protocol
												</span>
												<span className="text-base text-white-1">
													Pengalaman bekerja pada bagian Front End Developer,
													UI/UX Designer dan Technical Writer.
												</span>
												<a href="" className="text-right">
													<span className="text-sm font-bold underline text-brand">
														Go to Projects
													</span>
												</a>
											</div>
										</div>
										<div className="flex flex-col space-y-5 w-72">
											<div className="relative w-full overflow-hidden bg-black h-52 rounded-3xl">
												<Image
													layout="fill"
													src={ExampleProject}
													alt="project litedex"
												/>
											</div>
											<div className="flex flex-col p-1 space-y-3">
												<span className="text-lg font-bold text-brand">
													Litedex Protocol
												</span>
												<span className="text-base text-white-1">
													Pengalaman bekerja pada bagian Front End Developer,
													UI/UX Designer dan Technical Writer.
												</span>
												<a href="" className="text-right">
													<span className="text-sm font-bold underline text-brand">
														Go to Projects
													</span>
												</a>
											</div>
										</div>
									</div>
								</div>
							) : (
								tabProjects === "tab2" && (
									<div className="flex flex-col space-y-40">
										<div className="flex flex-col items-center justify-between space-y-5 lg:space-y-0 lg:flex-row">
											<div className="relative overflow-hidden shadow-2xl h-[13.125rem] w-[17.5rem] sm:h-[22.5rem] sm:w-[30rem] rounded-3xl">
												<Image
													layout="fill"
													src={ExampleProject}
													alt="project sindev"
												/>
											</div>
											<div className="flex flex-col space-y-3 lg:space-y-5 lg:w-[45%]">
												<h2 className="text-xl font-bold sm:text-2xl text-brand">
													Bakery Landing Page Design
												</h2>
												<p className="text-sm sm:text-base text-white-1">
													When an unknown printer took a galley of type and
													scrambled it to make a type specimen book. It has
													survived not only five centuries, but also the leap
													into electronic typesetting, remaining essentially
													unchanged.
												</p>
												<div className="flex flex-col">
													<span className="text-xs sm:text-sm text-white-1">
														1 Page
													</span>
													<span className="text-xs sm:text-sm text-white-1">
														100+ Words
													</span>
													<span className="text-xs sm:text-sm text-white-1">
														Design System
													</span>
													<span className="text-xs sm:text-sm text-white-1">
														Responsive
													</span>
												</div>
											</div>
										</div>
									</div>
								)
							)}
						</div>
					</div>
				</section>
				<section
					id="contact"
					className="relative w-full hidden lg:flex lg:justify-center bg-gradient-to-b from-transparent to-[#171045]"
				>
					<div className="pt-20 pb-40 space-y-2 sm:space-y-8">
						<h2 className="text-2xl font-bold text-center md:text-4xl text-brand">
							Contacts
						</h2>
						<div className="flex flex-row px-16 py-6 space-x-10 bg-gradient-to-tr from-brand to-transparent rounded-xl">
							<CompSocmed
								src={GlassInstragram}
								href={Ahref.instragramLink}
								name="Instragram"
							/>
							<CompSocmed
								src={GlassEmail}
								href={Ahref.emailLink}
								name="Email"
							/>
							<CompSocmed
								src={GlassLinkedIn}
								href={Ahref.linkedInLink}
								name="LinkedIn"
							/>
							<CompSocmed
								src={GlassGithub}
								href={Ahref.githubLink}
								name="Github"
							/>
						</div>
					</div>
				</section>
				<div className="absolute bottom-16 sm:bottom-0 z-[1] w-full border-t bg-main-dark/10 backdrop-blur-sm border-brand/30">
					<div className="flex items-center justify-center w-full py-6">
						<span className="text-sm font-medium text-center text-white ">
							© Copyright 2022 by Sindev. All Right Reserved.
						</span>
					</div>
				</div>
			</div>
		</div>
	);
}
